### ISSUE TITLE
Credênciais expostas

### ISSUE THREAD

**Issue by kazordoon** [Maransatto/rest-api-node-js#1]
As credênciais das variáveis de ambiente no nodemon.json estão expostas.
Recomendo criar um arquivo de exemplo para o nodemon.json (nodemon.json.example) e colocar o nodemon.json dentro do .gitignore.

**Comment by Maransatto** [comment]
Boa recomendação @kazordoon , de qualquer forma acho que neste projeto é interessante deixar aberto para fins didáticos, já que é o resultado das vídeo aulas do youtube
